5225 design weather screen
Melika-2000/WeatherProj pull request #1
Opened 2022-08-28 09:29 UTC by Melika-2000

jhbjn

2022-08-28 09:32 UTC, sajjadroudi commented
test

2022-08-28 09:34 UTC, sajjadroudi requested changes
test

2022-08-28 09:34 UTC, sajjadroudi commented on app/src/main/java/com/example/weatherproj/ui/weather/WeatherScreen.kt
> +        topBar = { TopBar(weather.isDay) },
test

2022-08-28 09:34 UTC, sajjadroudi commented on app/src/main/java/com/example/weatherproj/ui/weather/WeatherScreen.kt
> +        ) {
test 2

2022-08-28 09:53 UTC, sajjadroudi requested changes

2022-08-28 09:53 UTC, sajjadroudi commented on app/src/main/java/com/example/weatherproj/FakeData.kt
> +    val isDay: Boolean,
اسم کلاس بهتره همون Weather باشه.

2022-08-28 09:53 UTC, sajjadroudi commented on app/src/main/java/com/example/weatherproj/ui/theme/Color.kt
> +val Teal200 = Color(0xFF03DAC5)
این رنگ خیلی تاریکه.

2022-08-30 06:33 UTC, sajjadroudi requested changes

2022-08-30 06:33 UTC, sajjadroudi commented on app/src/main/java/com/example/weatherproj/ui/weather/WeatherScreen.kt
> +}
نیازی نیست این تابع Composable باشه چون داخلش هیچ فانکشن Composableی فراخوانی نمیکنه. 
از اونجا که Composable نیست، اسم تابع هم باید عوض بشه.
همچنین این تابع فقط در همین فایل استفاده میشه، بنابراین بهتره private باشه.

2022-08-30 06:33 UTC, sajjadroudi commented on app/src/main/java/com/example/weatherproj/ui/weather/WeatherScreen.kt
> +            TopRowInfo(weather = weather)
اسم پیشنهادی: `WeatherDetails`

2022-08-30 06:33 UTC, sajjadroudi commented on app/src/main/java/com/example/weatherproj/ui/weather/WeatherScreen.kt
> +            TemperatureDetail(temperature = weather.temperature)
اسم پیشنهادی: `WeatherTemperature`

2022-08-30 06:33 UTC, sajjadroudi commented on app/src/main/java/com/example/weatherproj/ui/weather/WeatherScreen.kt
> +        BackgroundSetter(isDay = weather.isDay)
اسم پیشنهادی: `WeatherBackground`

2022-08-30 06:33 UTC, sajjadroudi commented on app/src/main/java/com/example/weatherproj/ui/weather/WeatherScreen.kt
> +        BackgroundSetter(isDay = weather.isDay)
بهتره این تابع در روت تابع WeatherScreen فراخوانی شود، در ورودی یک composable lambda تعریف کند و به آن Scaffold، پاس داده شود.

2022-08-30 06:33 UTC, sajjadroudi commented on app/src/main/java/com/example/weatherproj/ui/weather/WeatherScreen.kt
> +    }
برای TopBar از TopAppBar composable function استفاده کنین.

2022-08-30 06:33 UTC, sajjadroudi commented on app/src/main/java/com/example/weatherproj/ui/weather/WeatherScreen.kt
> +
برای BottomBar بهتره از composable functionهای BottomNavigation و BottomNavigationItem استفاده کنین. البته برای این تسک ضرورتی نداره، ولی برای تسک پیاده‌سازی Navigation حتما این کار رو انجام بدین و از دو فانکشن مذکور استفاده کنین.

2022-08-30 06:33 UTC, sajjadroudi commented on app/src/main/java/com/example/weatherproj/ui/weather/WeatherScreen.kt
> +}
بهتره color و alpha هم در ورودی دریافت بشن، ولی مقدار default براشون ست بشه.

2022-08-30 06:33 UTC, sajjadroudi commented on app/src/main/java/com/example/weatherproj/ui/weather/WeatherScreen.kt
> +}
تغییر پیشنهادی مشابه کامنت فوق.

2022-08-30 06:33 UTC, sajjadroudi commented on app/src/main/java/com/example/weatherproj/ui/weather/WeatherScreen.kt
> +private fun TopRowInfo(weather: FakeWeather) {
اسم پیشنهادی: `WeatherDetails`

2022-08-30 06:33 UTC, sajjadroudi commented on app/src/main/java/com/example/weatherproj/ui/weather/WeatherScreen.kt
> +private fun WeatherComponent(iconId: Int, info: String) {
اسم پیشنهادی: `WeatherDetailsItem`

2022-08-30 06:33 UTC, sajjadroudi commented on app/src/main/java/com/example/weatherproj/FakeData.kt
> +    val moreDetail: String = ""
این فیلد اضافه هست.

2022-08-30 09:00 UTC, Melika-2000 commented on app/src/main/java/com/example/weatherproj/ui/weather/WeatherScreen.kt
> +}
done

2022-08-30 09:00 UTC, Melika-2000 commented on app/src/main/java/com/example/weatherproj/ui/weather/WeatherScreen.kt
> +            TemperatureDetail(temperature = weather.temperature)
done

2022-08-30 09:00 UTC, Melika-2000 commented on app/src/main/java/com/example/weatherproj/ui/weather/WeatherScreen.kt
> +        BackgroundSetter(isDay = weather.isDay)
done

2022-08-30 09:00 UTC, Melika-2000 commented on app/src/main/java/com/example/weatherproj/ui/weather/WeatherScreen.kt
> +        BackgroundSetter(isDay = weather.isDay)
done

2022-08-30 09:01 UTC, Melika-2000 commented on app/src/main/java/com/example/weatherproj/ui/weather/WeatherScreen.kt
> +
TODO added

2022-08-30 09:43 UTC, Melika-2000 commented on app/src/main/java/com/example/weatherproj/ui/weather/WeatherScreen.kt
> +    }
done

2022-08-30 09:45 UTC, Melika-2000 commented on app/src/main/java/com/example/weatherproj/ui/weather/WeatherScreen.kt
> +}
done

2022-08-30 09:46 UTC, Melika-2000 commented on app/src/main/java/com/example/weatherproj/FakeData.kt
> +    val moreDetail: String = ""
done

2022-08-30 09:46 UTC, Melika-2000 commented on app/src/main/java/com/example/weatherproj/ui/weather/WeatherScreen.kt
> +private fun WeatherComponent(iconId: Int, info: String) {
done

2022-08-30 09:46 UTC, Melika-2000 commented on app/src/main/java/com/example/weatherproj/ui/weather/WeatherScreen.kt
> +private fun TopRowInfo(weather: FakeWeather) {
done

2022-08-30 09:46 UTC, Melika-2000 commented on app/src/main/java/com/example/weatherproj/ui/weather/WeatherScreen.kt
> +}
done

2022-08-30 09:47 UTC, Melika-2000 commented on app/src/main/java/com/example/weatherproj/ui/weather/WeatherScreen.kt
> +            TopRowInfo(weather = weather)
done

2022-08-31 05:02 UTC, merged